### PR TITLE
Add universalviewer to Nurax

### PR DESCRIPTION
**Pull request by ghost**
This PR aligns Nurax with the latest Hyrax code which removes `pul_uv_rails` and instead relies on an iframe which embeds a viewer html file. The Hyrax installer now provides a default `uv.html` file and a default config file, plus a `package.json` that can be used to install universalviewer with yarn. 

Changes:
1) add the uv.html, uv_config.json and package.json files to nurax
2) upgrade the riiif version (whilst not necessary, this again brings Nurax into line with the latest Hyrax)

### CODE REVIEW

**Review by little9 — CHANGES_REQUESTED** [review]
There is a cleaner way of doing this that doesn't require including the UV 
code in the repo. If you look at the `package.json` for this project: https://github.com/UCLALibrary/ursus/blob/master/package.json

That downloads and recreates the UV installation when `rake assets:precompile` or `yarn install` is run
so you don't have to run a custom yarn command. 

It also moves the `uv.html` and `uv-config.json` from a non-public location so those can be configured/changed: `https://github.com/UCLALibrary/ursus/tree/master/config/uv`

**Comment by ghost** [comment]
Thanks @little9 I will do those improvements. I had seen some earlier code of yours (which inspired this approach) but not this work.

**Comment by ghost** [comment]
@little9 80 new files down to 6 🔢

**Review by little9 — APPROVED** [review]
:100:

**Pull request merged**
