### PR TITLE
Begin enabling optional features 

### LINKED ISSUE #8: Enable Hyrax bonus features
Enable the following bonus features for testing:

- [ ] Google Analytics
- [ ] BrowseEverything
- [x] ContactForm (may require 1-2 config tweaks?)
- [x] Citations
- [x] FFmpeg transcoding
- [ ] Geonames
- [x] Turn off requiring files for works
- [x] Virus checking
- [x] Sidekiq for background jobs?
- [x] At least 2 work-types with different fields 

Notes from planning meeting include: 
including getting API keys, generating configuration, etc. (Ideal to use a shared email address for these so not tied to a particular person.)

### PR DESCRIPTION
**Pull request by mjgiarlo**
Included in this PR are the following optional features (some incomplete -- see individual commits):

* BrowseEverything
* Virus checking
* Citations
* A/V transcoding
* Zero-file works
* Banner image
* Sidekiq for background jobs

Fixes #8

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@julesies @acozine :point_up: It's a start, anyway!

**Comment by mjgiarlo** [comment]
@julesies Outstanding technical work is:

- [ ] Set up continuous deployment
- [ ] Ensure `clamav` and `ffmpeg` are available on deployment host
- [ ] Come up with a way to handle config files with sensitive values
- [ ] Set up accounts for GeoNames, BrowseEverything, and Google Analytics
- [ ] Finish configuring GeoNames, BrowseEverything, and Google Analytics w/ above information

**Comment by julesies** [comment]
@mjgiarlo setting up accounts, I could do/provide right? Do we need browse-everything accounts for box, etc too?

Also, separate tickets for above might make sense now?

**Comment by mjgiarlo** [comment]
@julesies Yep, yep, yep!

**Comment by mjgiarlo** [comment]
Let's get CI passing on the `master` branch, and make sure `master` is continuously deploying to demo.curationexperts.com, before merging this PR.

**Pull request merged**
