### PR TITLE
Add cjcolvar to admin group

### PR DESCRIPTION
**Pull request by cjcolvar**
I need to do a gap analysis for work on Avalon 7 so I need admin access to fully test out the system.

### CODE REVIEW

**Review by bess — APPROVED** [review]

**Comment by bess** [comment]
@cjcolvar I approved your PR but you should check with @elrayle and @mjgiarlo -- I'm not sure it's the master branch that's currently being deployed, so being in the role map of the master branch might not get you the access you're looking for.

**Comment by cjcolvar** [comment]
@bess I'll do that.  Thanks!

**Comment by elrayle** [comment]
@cjcolvar Nurax is set to do QA testing of the collections-sprint branch.

**Comment by cjcolvar** [comment]
That actually sounds good to me as long as it doesn't disrupt the testing.

**Pull request merged**
